### ISSUE TITLE
Can we build index on original data but prune by the distance between transformed vectors and queries?

### ISSUE THREAD

**Issue by CaucherWang** [gaoj0017/ADSampling#2]
In this way, we can conduct experiments more fairly.

**Comment by CaucherWang** [comment]
Also, we can keep the original vectors. If we directly evict them from memory, it is more or less radical.

**Comment by gaoj0017** [comment]
For the first comment, they are equivalent. This is because for IVF and HNSW, the construction depends only on the distance between vectors and the transformation does not distort the distances. For other indexes, yes, users can construct the indexes with the original vectors and transform the vectors afterwards.

For the second comment, it depends on the needs, but in general, I think it is unnecessary to keep them (as it will have double sized space consumption). If the users only target the IDs of the KNN objects, the original vectors will not be used. If the original vectors are required, the algorithm can also inversely transforming the vectors at the end of the algorithm.

**Comment by CaucherWang** [comment]
> For the first comment, they are equivalent. This is because for IVF and HNSW, the construction depends only on the distance between vectors and the transformation does not distort the distances. For other indexes, yes, users can construct the indexes with the original vectors and transform the vectors afterwards.
> 
> For the second comment, it depends on the needs, but in general, I think it is unnecessary to keep them (as it will have double sized space consumption). If the users only target the IDs of the KNN objects, the original vectors will not be used. If the original vectors are required, the algorithm can also inversely transforming the vectors at the end of the algorithm.

Very good.  Strong paper!

**Comment by CaucherWang** [comment]
> For the first comment, they are equivalent. This is because for IVF and HNSW, the construction depends only on the distance between vectors and the transformation does not distort the distances. For other indexes, yes, users can construct the indexes with the original vectors and transform the vectors afterwards.
> 
> For the second comment, it depends on the needs, but in general, I think it is unnecessary to keep them (as it will have double sized space consumption). If the users only target the IDs of the KNN objects, the original vectors will not be used. If the original vectors are required, the algorithm can also inversely transforming the vectors at the end of the algorithm.

Very good. 
By the way, congrats on the acceptance of your wonderful work in Sigmod!

**Comment by gaoj0017** [comment]
Thank you for your kind congratulations and comments. Have a good day :)

**Comment by CaucherWang** [comment]
PROGRESS: I have tried this idea, but the performance degrades. The reason might be the frequent memory access to find the transformed vectors of candidate during distance calculation.

**Comment by gaoj0017** [comment]
It might be due to the implementation. The transformed vectors are supposed to be stored where the original vectors are (i.e., to replace the original vectors). In this case, it will not introduce extra costs of finding the transformed vectors.

**Comment by CaucherWang** [comment]
Exactly.
